### PR TITLE
Get rid of jsonrpsee

### LINKED ISSUE #47: Deps Broken
Fixed in https://github.com/chevdor/subwasm/pull/44
Re-introduced in https://github.com/chevdor/subwasm/commit/113e0afdf58b22951bf8fe46b036f19a70e51605

### PR DESCRIPTION
**Pull request by AurevoirXavier**
1. jsonrpsee is an overkill dep; reduce around 50+ deps in this PR
2. accept wss without a port, no need to write `rpc.polkadot.io:443` anymore, just `rpc.polkadot.io`
3. we don't need async for just fetching one storage item from the node
4. closes #47

### CODE REVIEW

File: libs/wasm-loader/src/lib.rs [hunk 1]
```diff
@@ -175,6 +199,13 @@ mod tests {
 	// 	assert!(wasm.len() > 1_000_000);
 	// }
 
+	#[test]
+	#[ignore = "needs node"]
+	fn fetch_should_work() {
+		assert!(WasmLoader::fetch_wasm(&OnchainBlock::new("https://rpc.polkadot.io", None)).is_ok());
+		assert!(WasmLoader::fetch_wasm(&OnchainBlock::new(&get_ws_node(), None)).is_ok());
```
Comment (AurevoirXavier) [inline libs/wasm-loader/src/lib.rs:206]: Because Polkadot enabled cloudflare.

**Comment by chevdor** [comment]
Thanks for the PR @AurevoirXavier

**Review by chevdor — APPROVED** [review]
